"""
Edge Detector & Signal Generator — The Brain

Combines ALL analysis engines to produce actionable trade signals.
Routes each market to the right analyzer based on category/subcategory.

Signal types:
1. CONFIRMED_BUY — near-certain outcome, free money (confidence > 0.85)
2. STRONG_BUY — high edge from data arb (edge > 15%)
3. BUY — moderate edge from news/polling (edge > 8%)
4. HOLD — existing position, thesis intact
5. SELL — narrative shifted, cut losses
6. BUY_MORE — narrative strengthened, add to winner
"""

import asyncio
import time
from typing import Dict, List, Optional
from dataclasses import dataclass, field
from enum import Enum

from config.settings import Settings
from scanner.market_scanner import MarketSnapshot, MarketScanner
from analysis.confirmed_events import ConfirmedEventDetector, ConfirmedSignal
from analysis.news_llm import LLMAnalyzer, get_llm_analyzer
from analysis.finance_data import FinanceDataEngine
from analysis.elections import ElectionAnalyzer
from analysis.youtube import YouTubeAnalyzer
from analysis.sports import SportsAnalyzer
from analysis.narrative import NarrativeShiftDetector
from analysis.price_divergence import PriceProbabilityDivergenceDetector
from analysis.volume_overreaction import VolumeAccelerationDetector, OverreactionDetector
from strategy.multi_outcome_arb import MultiOutcomeArbitrageEngine, ArbitrageOpportunity


class SignalType(Enum):
    CONFIRMED_BUY = "CONFIRMED_BUY"
    STRONG_BUY = "STRONG_BUY"
    BUY = "BUY"
    HOLD = "HOLD"
    SELL = "SELL"
    BUY_MORE = "BUY_MORE"
    REDUCE = "REDUCE"
    SKIP = "SKIP"


@dataclass
class Signal:
    """A trade signal generated by the edge detector."""
    signal_type: SignalType
    market_question: str
    condition_id: str
    token_id: str
    outcome: str  # "yes" or "no"
    current_price: float
    estimated_probability: float
    edge_percent: float  # (est_prob - price) * 100
    confidence: float
    reasoning: str
    category: str
    subcategory: str
    source: str  # which engine generated this
    suggested_amount_usd: float = 0
    generated_at: float = 0
    snapshot: Optional[MarketSnapshot] = None

    @property
    def edge_direction(self) -> str:
        """Is market underpriced (buy) or overpriced (sell)?"""
        return "underpriced" if self.edge_percent > 0 else "overpriced"

    @property
    def risk_reward_ratio(self) -> float:
        """Expected profit / potential loss."""
        if self.current_price <= 0 or self.current_price >= 1:
            return 0
        potential_profit = (1.0 - self.current_price)
        potential_loss = self.current_price
        return potential_profit / potential_loss

    def __str__(self):
        emoji = {
            SignalType.CONFIRMED_BUY: "💎",
            SignalType.STRONG_BUY: "🔥",
            SignalType.BUY: "📈",
            SignalType.HOLD: "🔄",
            SignalType.SELL: "📉",
            SignalType.BUY_MORE: "⬆️",
            SignalType.REDUCE: "⬇️",
            SignalType.SKIP: "⏭️",
        }.get(self.signal_type, "❓")
        return (
            f"{emoji} {self.signal_type.value} | {self.outcome.upper()} @ {self.current_price:.2f} | "
            f"Edge: {self.edge_percent:+.1f}% | {self.market_question[:50]}"
        )


class EdgeDetector:
    """
    Central intelligence — routes markets to analysis engines and generates signals.
    
    Architecture:
    Scanner → EdgeDetector → [ConfirmedEvents, FinanceData, Elections, YouTube, Sports, News] → Signals → Trader
    """

    def __init__(self, scanner: Optional[MarketScanner] = None):
        self.scanner = scanner
        self.llm = get_llm_analyzer()

        # Analysis engines
        self.confirmed_detector = ConfirmedEventDetector(self.llm)
        self.finance_engine = FinanceDataEngine()
        self.election_analyzer = ElectionAnalyzer(self.llm)
        self.youtube_analyzer = YouTubeAnalyzer()
        self.sports_analyzer = SportsAnalyzer(self.llm)
        self.narrative_detector = NarrativeShiftDetector(self.llm)
        self.divergence_detector = PriceProbabilityDivergenceDetector()
        self.volume_detector = VolumeAccelerationDetector()
        self.overreaction_detector = OverreactionDetector()
        self.multi_arb = MultiOutcomeArbitrageEngine()

        # Signal history (for deduplication)
        self._recent_signals: Dict[str, float] = {}  # condition_id -> last_signal_time
        self._signal_cooldown = 1800  # 30 min between signals for same market

        # Stats
        self.signals_generated = 0
        self.markets_analyzed = 0

    async def analyze_all(self, snapshots: List[MarketSnapshot]) -> List[Signal]:
        """
        Analyze all snapshots and generate signals.
        This is the main entry point called after each scan.
        """
        t0 = time.time()
        all_signals = []

        # ── Stage 1: Confirmed Events (highest priority, fastest) ──
        confirmed_signals = await self.confirmed_detector.scan(snapshots)
        for cs in confirmed_signals:
            signal = self._confirmed_to_signal(cs)
            if signal and self._should_emit(signal):
                all_signals.append(signal)

        # ── Stage 2: Route by category to specialized engines ──
        # Group snapshots by category
        by_category: Dict[str, List[MarketSnapshot]] = {}
        for snap in snapshots:
            by_category.setdefault(snap.category, []).append(snap)

        # Run analysis engines in parallel
        tasks = []

        # Finance markets → FinanceDataEngine
        for snap in by_category.get("finance", []):
            tasks.append(self._analyze_finance(snap))

        # Politics → ElectionAnalyzer
        for snap in by_category.get("politics", []):
            tasks.append(self._analyze_election(snap))

        # Culture (YouTube markets) → YouTubeAnalyzer
        for snap in by_category.get("culture", []):
            if snap.subcategory in ("mrbeast", "youtube"):
                tasks.append(self._analyze_youtube(snap))
            else:
                tasks.append(self._analyze_with_llm(snap))

        # Sports → SportsAnalyzer
        for snap in by_category.get("sports", []):
            tasks.append(self._analyze_sports(snap))

        # Geopolitics, Crypto, Science → LLM
        for cat in ("geopolitics", "crypto", "science", "other"):
            for snap in by_category.get(cat, []):
                tasks.append(self._analyze_with_llm(snap))

        # Run all analyses (with concurrency limit)
        if tasks:
            results = await asyncio.gather(*tasks, return_exceptions=True)
            for result in results:
                if isinstance(result, Signal) and result.signal_type != SignalType.SKIP:
                    if self._should_emit(result):
                        all_signals.append(result)

        # ── Stage 3: Check narrative shifts for tracked positions ──
        narratives = await self.narrative_detector.check_all()

        # ── Stage 3b: Divergence, Volume, Overreaction ──
        # Price-probability divergence (Feature #1: 84% accuracy at >15pt)
        div_signals = self.divergence_detector.scan_all(snapshots)
        for div in div_signals:
            sig_type = SignalType.STRONG_BUY if div.is_strong else SignalType.BUY
            token = None
            price = div.market_price
            if div.buy_side == "yes":
                for snap in snapshots:
                    if snap.condition_id == div.condition_id:
                        token = snap.market.yes_token
                        break
            else:
                for snap in snapshots:
                    if snap.condition_id == div.condition_id:
                        token = snap.market.no_token
                        price = 1 - div.market_price
                        break
            if token:
                sig = Signal(
                    signal_type=sig_type,
                    market_question=div.question,
                    condition_id=div.condition_id,
                    token_id=token.token_id,
                    outcome=div.buy_side,
                    current_price=price,
                    estimated_probability=div.external_prob if div.buy_side == "yes" else (1 - div.external_prob),
                    edge_percent=div.divergence_pts,
                    confidence=div.confidence,
                    reasoning=div.reasoning,
                    category=div.category,
                    subcategory="divergence",
                    source=f"Divergence/{div.source}",
                    suggested_amount_usd=self._calculate_position_size(
                        div.divergence_pts, div.confidence, price
                    ),
                    generated_at=time.time(),
                )
                if self._should_emit(sig):
                    all_signals.append(sig)

        # Overreaction detection (Feature #3: mean reversion)
        for snap in snapshots:
            overreaction = self.overreaction_detector.detect(
                snap.market, snap.yes_price
            )
            if overreaction:
                token = (snap.market.yes_token if overreaction.suggested_side == "yes"
                         else snap.market.no_token)
                if token:
                    sig = Signal(
                        signal_type=SignalType.BUY,
                        market_question=snap.market.question,
                        condition_id=snap.market.condition_id,
                        token_id=token.token_id,
                        outcome=overreaction.suggested_side,
                        current_price=overreaction.suggested_entry,
                        estimated_probability=overreaction.suggested_target,
                        edge_percent=overreaction.edge_pct,
                        confidence=overreaction.reversion_probability * 0.8,
                        reasoning=f"Overreaction: {overreaction.move_pct:+.1f}% move, "
                                  f"serial corr={overreaction.serial_correlation:.2f}, "
                                  f"reversion prob={overreaction.reversion_probability:.0%}",
                        category=snap.category,
                        subcategory="overreaction",
                        source="OverreactionDetector",
                        suggested_amount_usd=self._calculate_position_size(
                            overreaction.edge_pct, overreaction.reversion_probability * 0.8,
                            overreaction.suggested_entry
                        ),
                        generated_at=time.time(),
                    )
                    if self._should_emit(sig):
                        all_signals.append(sig)

        # Volume spike alerts (record + detect)
        for snap in snapshots:
            vol = snap.market.volume if hasattr(snap.market, 'volume') else 0
            self.volume_detector.record(snap.condition_id, vol, snap.yes_price)

        # ── Stage 4: Multi-Outcome Arbitrage (guaranteed profit) ──
        # Extract unique events from snapshots
        events_seen = {}
        for snap in snapshots:
            eid = snap.event.event_id
            if eid not in events_seen:
                events_seen[eid] = snap.event
        if events_seen:
            try:
                arb_opps = await self.multi_arb.scan_all_events(list(events_seen.values()))
                for opp in arb_opps:
                    sig_type = SignalType.CONFIRMED_BUY if opp.is_guaranteed else SignalType.STRONG_BUY
                    for leg in opp.legs:
                        sig = Signal(
                            signal_type=sig_type,
                            market_question=f"[ARB] {opp.event_title}",
                            condition_id=leg.get('condition_id', opp.event_id),
                            token_id=leg.get('token_id', ''),
                            outcome=leg.get('outcome', 'no'),
                            current_price=leg.get('price', 0),
                            estimated_probability=1.0 if opp.is_guaranteed else opp.confidence,
                            edge_percent=opp.profit_pct,
                            confidence=opp.confidence,
                            reasoning=opp.reasoning,
                            category="arbitrage",
                            subcategory=opp.opportunity_type,
                            source="MultiOutcomeArb",
                            suggested_amount_usd=leg.get('amount_usd', opp.suggested_total_usd / max(len(opp.legs), 1)),
                            generated_at=time.time(),
                        )
                        if self._should_emit(sig):
                            all_signals.append(sig)
            except Exception as e:
                print(f"⚠️ Multi-outcome arb error: {e}")

        for shift in narratives:
            signal_type = {
                "SELL": SignalType.SELL,
                "BUY_MORE": SignalType.BUY_MORE,
                "REDUCE": SignalType.REDUCE,
                "HOLD": SignalType.HOLD,
            }.get(shift.recommendation, SignalType.HOLD)

            all_signals.append(Signal(
                signal_type=signal_type,
                market_question=shift.position.question,
                condition_id=shift.position.condition_id,
                token_id=shift.position.token_id,
                outcome=shift.position.outcome,
                current_price=shift.position.current_price,
                estimated_probability=shift.new_probability,
                edge_percent=(shift.new_probability - shift.position.current_price) * 100,
                confidence=0.6,
                reasoning=shift.reasoning,
                category="position",
                subcategory=shift.shift_type,
                source="NarrativeShift",
                generated_at=time.time(),
            ))

        # Sort: confirmed first, then by edge size
        all_signals.sort(key=lambda s: (
            0 if s.signal_type == SignalType.CONFIRMED_BUY else
            1 if s.signal_type == SignalType.STRONG_BUY else
            2 if s.signal_type == SignalType.SELL else
            3 if s.signal_type == SignalType.BUY else 4,
            -abs(s.edge_percent)
        ))

        elapsed = time.time() - t0
        self.signals_generated += len(all_signals)
        self.markets_analyzed += len(snapshots)
        print(f"🧠 Edge detection: {len(all_signals)} signals from {len(snapshots)} markets ({elapsed:.1f}s)")

        return all_signals

    # ═══════════════════════════════════════════════════════════════
    # ANALYSIS ROUTING
    # ═══════════════════════════════════════════════════════════════

    async def _analyze_finance(self, snap: MarketSnapshot) -> Optional[Signal]:
        """Route to finance data engine."""
        try:
            analysis = await self.finance_engine.analyze_market(snap)
            if not analysis:
                return None
            # Feed probability into divergence detector
            self.divergence_detector.register_estimate(
                snap.condition_id, analysis.probability_estimate, "finance_data"
            )
            return self._analysis_to_signal(
                snap, analysis.probability_estimate, analysis.confidence,
                analysis.reasoning, "FinanceData"
            )
        except Exception as e:
            print(f"⚠️ Finance analysis error: {e}")
            return None

    async def _analyze_election(self, snap: MarketSnapshot) -> Optional[Signal]:
        """Route to election analyzer."""
        try:
            analysis = await self.election_analyzer.analyze_market(snap)
            if not analysis:
                return None
            self.divergence_detector.register_estimate(
                snap.condition_id, analysis.probability_estimate, "polling"
            )
            return self._analysis_to_signal(
                snap, analysis.probability_estimate, analysis.confidence,
                analysis.reasoning, "Elections"
            )
        except Exception as e:
            print(f"⚠️ Election analysis error: {e}")
            return None

    async def _analyze_youtube(self, snap: MarketSnapshot) -> Optional[Signal]:
        """Route to YouTube analyzer."""
        try:
            analysis = await self.youtube_analyzer.analyze_market(snap.market.question)
            if not analysis:
                return None
            self.divergence_detector.register_estimate(
                snap.condition_id, analysis.probability_estimate, "youtube"
            )
            return self._analysis_to_signal(
                snap, analysis.probability_estimate, analysis.confidence,
                analysis.reasoning, "YouTube"
            )
        except Exception as e:
            print(f"⚠️ YouTube analysis error: {e}")
            return None

    async def _analyze_sports(self, snap: MarketSnapshot) -> Optional[Signal]:
        """Route to sports analyzer."""
        try:
            analysis = await self.sports_analyzer.analyze_market(snap)
            if not analysis:
                return None
            self.divergence_detector.register_estimate(
                snap.condition_id, analysis.probability_estimate, "sports_data"
            )
            return self._analysis_to_signal(
                snap, analysis.probability_estimate, analysis.confidence,
                analysis.reasoning, "Sports"
            )
        except Exception as e:
            print(f"⚠️ Sports analysis error: {e}")
            return None

    async def _analyze_with_llm(self, snap: MarketSnapshot) -> Optional[Signal]:
        """Generic LLM analysis for any category."""
        if not Settings.has_llm():
            return None
        try:
            analysis = await self.llm.analyze_market(
                snap.market.question,
                additional_context=(
                    f"Category: {snap.category}. "
                    f"Event: {snap.event.title}. "
                    f"Current price: YES={snap.market.best_yes_price:.2f}."
                )
            )
            if not analysis:
                return None
            self.divergence_detector.register_estimate(
                snap.condition_id, analysis.probability_estimate, "llm"
            )
            return self._analysis_to_signal(
                snap, analysis.probability_estimate, analysis.confidence,
                analysis.reasoning, "LLM"
            )
        except Exception as e:
            print(f"⚠️ LLM analysis error: {e}")
            return None

    # ═══════════════════════════════════════════════════════════════
    # SIGNAL CONSTRUCTION
    # ═══════════════════════════════════════════════════════════════

    def _confirmed_to_signal(self, cs: ConfirmedSignal) -> Optional[Signal]:
        """Convert ConfirmedSignal to Signal."""
        return Signal(
            signal_type=SignalType.CONFIRMED_BUY,
            market_question=cs.snapshot.market.question,
            condition_id=cs.snapshot.market.condition_id,
            token_id=cs.confirmed_token_id,
            outcome=cs.confirmed_outcome,
            current_price=cs.current_price,
            estimated_probability=0.98,
            edge_percent=cs.edge_percent,
            confidence=cs.confidence,
            reasoning=cs.reason,
            category=cs.snapshot.category,
            subcategory=cs.snapshot.subcategory,
            source="ConfirmedEvent",
            suggested_amount_usd=self._calculate_position_size(
                cs.edge_percent, cs.confidence, cs.current_price
            ),
            generated_at=time.time(),
            snapshot=cs.snapshot,
        )

    def _analysis_to_signal(self, snap: MarketSnapshot,
                             est_prob: float, confidence: float,
                             reasoning: str, source: str) -> Optional[Signal]:
        """Convert an analysis result into a trade signal."""
        yes_price = snap.market.best_yes_price

        # Determine edge on YES side
        yes_edge = (est_prob - yes_price) * 100
        # Also check NO side: if est_prob < price, NO is underpriced
        no_edge = ((1 - est_prob) - (1 - yes_price)) * 100  # = yes_price - est_prob

        # Choose the side with the bigger edge
        if abs(yes_edge) >= abs(no_edge) and yes_edge > 0:
            outcome = "yes"
            token = snap.market.yes_token
            edge = yes_edge
            price = yes_price
        elif no_edge > 0:
            outcome = "no"
            token = snap.market.no_token
            edge = no_edge
            price = 1 - yes_price
        else:
            # No edge — skip
            return Signal(
                signal_type=SignalType.SKIP,
                market_question=snap.market.question,
                condition_id=snap.market.condition_id,
                token_id="",
                outcome="none",
                current_price=yes_price,
                estimated_probability=est_prob,
                edge_percent=max(yes_edge, no_edge),
                confidence=confidence,
                reasoning=reasoning,
                category=snap.category,
                subcategory=snap.subcategory,
                source=source,
                generated_at=time.time(),
                snapshot=snap,
            )

        if not token:
            return None

        # Determine signal type based on edge + confidence
        min_edge = Settings.MIN_EDGE_PERCENT
        high_edge = Settings.HIGH_EDGE_PERCENT

        if edge >= high_edge and confidence >= 0.7:
            sig_type = SignalType.STRONG_BUY
        elif edge >= min_edge and confidence >= 0.4:
            sig_type = SignalType.BUY
        else:
            sig_type = SignalType.SKIP

        return Signal(
            signal_type=sig_type,
            market_question=snap.market.question,
            condition_id=snap.market.condition_id,
            token_id=token.token_id,
            outcome=outcome,
            current_price=price,
            estimated_probability=est_prob if outcome == "yes" else (1 - est_prob),
            edge_percent=edge,
            confidence=confidence,
            reasoning=reasoning,
            category=snap.category,
            subcategory=snap.subcategory,
            source=source,
            suggested_amount_usd=self._calculate_position_size(edge, confidence, price),
            generated_at=time.time(),
            snapshot=snap,
        )

    def _should_emit(self, signal: Signal) -> bool:
        """Check if signal should be emitted (deduplication + cooldown)."""
        if signal.signal_type == SignalType.SKIP:
            return False

        last = self._recent_signals.get(signal.condition_id, 0)
        if time.time() - last < self._signal_cooldown:
            return False

        self._recent_signals[signal.condition_id] = time.time()
        return True

    def _calculate_position_size(self, edge_pct: float, confidence: float,
                                  price: float) -> float:
        """
        Kelly-inspired position sizing.
        
        Full Kelly: f = (p*b - q) / b
        where p=win prob, q=loss prob, b=odds
        We use fractional Kelly (25%) for safety.
        """
        # Effective probability
        p = min(0.95, max(0.05, price + edge_pct / 100))
        q = 1 - p
        b = (1.0 - price) / price if price > 0 else 1  # odds

        if b <= 0:
            return Settings.MIN_TRADE_USD

        kelly = (p * b - q) / b
        kelly = max(0, min(1, kelly))

        # Fractional Kelly (25%) * confidence
        fraction = kelly * 0.25 * confidence

        # Scale to trade limits
        amount = fraction * Settings.MAX_POSITION_USD
        amount = max(Settings.MIN_TRADE_USD, min(Settings.MAX_TRADE_USD, amount))

        return round(amount, 2)
